n26:
  finance:
    monitoring:
      api:
        endpoint:
          statistics: '/statistics'
          transactions: '/transactions'
        threshold: 60000
        breathe: 5000
        maintain-interval: 1000
