n26:
  finance:
    monitoring:
      api:
        endpoint:
          statistics: '/statistics'
          transactions: '/transactions'
        repository:
          unit: 1000
          space: 5
          length: 60
